/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiInterface;

import Game.HouseBreak;
import Game.Starter;
import Utente.User;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author burritos
 */
public class SalvataggiForm extends javax.swing.JFrame {
    User giocatore = null;
    /**
     * Creates new form Salvataggi
     * @param giocatoreAttuale giocatore della sessione
     */
    public SalvataggiForm(User giocatoreAttuale) {
        initComponents();
        giocatore = giocatoreAttuale;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pannelloSalvataggio = new javax.swing.JPanel();
        goBackButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabellaSalvataggi = new javax.swing.JTable();
        labelData = new javax.swing.JLabel();
        caricaButton = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        caricaButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 400));
        setResizable(false);

        pannelloSalvataggio.setBackground(new java.awt.Color(47, 54, 64));
        pannelloSalvataggio.setForeground(new java.awt.Color(255, 255, 255));

        goBackButton.setBackground(new java.awt.Color(47, 54, 64));
        goBackButton.setFont(new java.awt.Font("URW Gothic L", 1, 48)); // NOI18N
        goBackButton.setForeground(new java.awt.Color(255, 255, 255));
        goBackButton.setText("<-");
        goBackButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        goBackButton.setBorderPainted(false);
        goBackButton.setContentAreaFilled(false);
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        tabellaSalvataggi.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tabellaSalvataggi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODICE", "DATA", "STANZA", "VITA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabellaSalvataggi.setToolTipText("");
        tabellaSalvataggi.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tabellaSalvataggi.setGridColor(new java.awt.Color(204, 204, 204));
        tabellaSalvataggi.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tabellaSalvataggi.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabellaSalvataggi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaSalvataggi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabellaSalvataggi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabellaSalvataggiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabellaSalvataggi);

        labelData.setForeground(new java.awt.Color(255, 255, 255));
        labelData.setText("jLabel1");

        caricaButton.setBackground(new java.awt.Color(47, 54, 64));
        caricaButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        caricaButton.setForeground(new java.awt.Color(255, 255, 255));
        caricaButton.setText("Carica");
        caricaButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        caricaButton.setBorderPainted(false);
        caricaButton.setEnabled(false);
        caricaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caricaButtonActionPerformed(evt);
            }
        });

        labelLogo.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setText("Partite salvate");

        caricaButton1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        caricaButton1.setText("Nuova partita");
        caricaButton1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        caricaButton1.setBorderPainted(false);
        caricaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caricaButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannelloSalvataggioLayout = new javax.swing.GroupLayout(pannelloSalvataggio);
        pannelloSalvataggio.setLayout(pannelloSalvataggioLayout);
        pannelloSalvataggioLayout.setHorizontalGroup(
            pannelloSalvataggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloSalvataggioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pannelloSalvataggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannelloSalvataggioLayout.createSequentialGroup()
                        .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(labelLogo))
                    .addGroup(pannelloSalvataggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pannelloSalvataggioLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(labelData)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caricaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(caricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pannelloSalvataggioLayout.setVerticalGroup(
            pannelloSalvataggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloSalvataggioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannelloSalvataggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogo)
                    .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannelloSalvataggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caricaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caricaButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelData))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelloSalvataggio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelloSalvataggio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        //chiuse il form
        this.dispose();
        ChoiceFrame scelte = new ChoiceFrame(giocatore);
        scelte.setVisible(true);
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void tabellaSalvataggiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabellaSalvataggiMouseClicked
        int row = tabellaSalvataggi.getSelectedRow();
        if(row != -1){
            caricaButton.setEnabled(true);
        }
    }//GEN-LAST:event_tabellaSalvataggiMouseClicked

    private void caricaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caricaButtonActionPerformed
        int row = tabellaSalvataggi.getSelectedRow();
        String prova = tabellaSalvataggi.getModel().getValueAt(row, 1).toString();
        labelData.setText(prova);

    }//GEN-LAST:event_caricaButtonActionPerformed

    private void caricaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caricaButton1ActionPerformed
        //nascono il form per il login e registrazione
        this.setVisible(false);
        
        Starter gioco= new Starter(new HouseBreak());
        gioco.run();
    }//GEN-LAST:event_caricaButton1ActionPerformed
    
    private void addElementiTable(){
        //Aggiunge elementi
        DefaultTableModel model;
        model = (DefaultTableModel) tabellaSalvataggi.getModel();
        model.addRow(new Object[]{"ciao","stazna","40"});
        model.addRow(new Object[]{"data","Cazzo","12"});
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalvataggiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalvataggiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalvataggiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalvataggiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton caricaButton;
    private javax.swing.JButton caricaButton1;
    private javax.swing.JButton goBackButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JPanel pannelloSalvataggio;
    private javax.swing.JTable tabellaSalvataggi;
    // End of variables declaration//GEN-END:variables
}
